/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import { number, optional, string, unknown } from '../schema';
import { BaseController } from './baseController';

export class AirtimeCommissionsController extends BaseController {
  /**
   * @param accept        Example: application/com.reloadly.topups-v1+json
   * @param authorization
   * @param size          This indicates the number of operators offering discounts to be retrieved on a
   *                                page. Default value is 200.
   * @param page          This indicates the page of the discounts list being retrieved. Default value is 1.
   * @return Response from the API call
   */
  async reloadlyAirtimeCommissions(
    accept: string,
    authorization: string,
    size?: number,
    page?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/operators/commissions');
    req.baseUrl('Airtime');
    const mapped = req.prepareArgs({
      accept: [accept, string()],
      authorization: [authorization, string()],
      size: [size, optional(number())],
      page: [page, optional(number())],
    });
    req.header('Accept', mapped.accept);
    req.header('Authorization', mapped.authorization);
    req.query('size', mapped.size);
    req.query('page', mapped.page);
    req.throwOn(401, ApiError, 'Full authentication is required to access this resource');
    req.throwOn(404, ApiError, 'Not Found');
    req.authenticate(false);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param accept
   * @param authorization
   * @param operatorid
   * @return Response from the API call
   */
  async reloadlyAirtimeCommissionById(
    accept: string,
    authorization: string,
    operatorid: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET');
    req.baseUrl('Airtime');
    const mapped = req.prepareArgs({
      accept: [accept, string()],
      authorization: [authorization, string()],
      operatorid: [operatorid, string()],
    });
    req.header('Accept', mapped.accept);
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/operators/${mapped.operatorid}/commissions`;
    req.throwOn(401, ApiError, 'Full authentication is required to access this resource');
    req.throwOn(404, ApiError, 'Operator not found for given ID');
    req.authenticate(false);
    return req.callAsJson(unknown(), requestOptions);
  }
}
