/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import { number, string, unknown } from '../schema';
import { BaseController } from './baseController';

export class GiftCardsOrdersController extends BaseController {
  /**
   * @param accept
   * @param authorization
   * @param transactionid Indicates the transaction identification number of the gift card's redeem code to
   *                                be retrieved.
   * @return Response from the API call
   */
  async reloadlyGiftCardsRedeemCodes(
    accept: string,
    authorization: string,
    transactionid: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET');
    req.baseUrl('Gift Cards');
    const mapped = req.prepareArgs({
      accept: [accept, string()],
      authorization: [authorization, string()],
      transactionid: [transactionid, number()],
    });
    req.header('Accept', mapped.accept);
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/orders/transactions/${mapped.transactionid}/cards`;
    req.throwOn(401, ApiError, 'Full authentication is required to access this resource');
    req.throwOn(404, ApiError, 'Invalid transaction ID');
    req.authenticate(false);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param accept
   * @param authorization
   * @param body          Request Payload
   * @return Response from the API call
   */
  async reloadlyGiftCardsOrders(
    accept: string,
    authorization: string,
    body: unknown,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/orders');
    req.baseUrl('Gift Cards');
    const mapped = req.prepareArgs({
      accept: [accept, string()],
      authorization: [authorization, string()],
      body: [body, unknown()],
    });
    req.header('Accept', mapped.accept);
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Invalid price, please ensure you selected the right price');
    req.throwOn(401, ApiError, 'Full authentication is required to access this resource');
    req.throwOn(404, ApiError, 'Not found');
    req.authenticate(false);
    return req.callAsJson(unknown(), requestOptions);
  }
}
