/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import {
  ReloadlyUtilityPaymentsPayBillRequest,
  reloadlyUtilityPaymentsPayBillRequestSchema,
} from '../models/reloadlyUtilityPaymentsPayBillRequest';
import { string, unknown } from '../schema';
import { BaseController } from './baseController';

export class UtilityPaymentsPayBillController extends BaseController {
  /**
   * @param accept
   * @param authorization
   * @param body          Request Payload
   * @return Response from the API call
   */
  async reloadlyUtilityPaymentsPayBill(
    accept: string,
    authorization: string,
    body: ReloadlyUtilityPaymentsPayBillRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/pay');
    req.baseUrl('Utility Payments');
    const mapped = req.prepareArgs({
      accept: [accept, string()],
      authorization: [authorization, string()],
      body: [body, reloadlyUtilityPaymentsPayBillRequestSchema],
    });
    req.header('Accept', mapped.accept);
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(401, ApiError, 'Full authentication is required to access this resource');
    req.throwOn(404, ApiError, 'Not Found');
    req.authenticate(false);
    return req.callAsJson(unknown(), requestOptions);
  }
}
