/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RecipientPhoneDetails {
  countryCode: string;
  phoneNumber: string;
}

export const recipientPhoneDetailsSchema: Schema<RecipientPhoneDetails> = object(
  {
    countryCode: ['countryCode', string()],
    phoneNumber: ['phoneNumber', string()],
  }
);
