/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ReloadlyAirtimeFxRatesRequest {
  operatorId: string;
  amount: string;
}

export const reloadlyAirtimeFxRatesRequestSchema: Schema<ReloadlyAirtimeFxRatesRequest> = object(
  { operatorId: ['operatorId', string()], amount: ['amount', string()] }
);
