/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';

export interface ReloadlyUtilityPaymentsPayBillRequest {
  subscriberAccountNumber: string;
  amount: number;
  billerId: number;
  useLocalAmount: boolean;
}

export const reloadlyUtilityPaymentsPayBillRequestSchema: Schema<ReloadlyUtilityPaymentsPayBillRequest> = object(
  {
    subscriberAccountNumber: ['subscriberAccountNumber', string()],
    amount: ['amount', number()],
    billerId: ['billerId', number()],
    useLocalAmount: ['useLocalAmount', boolean()],
  }
);
