/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import {
  RecipientPhoneDetails,
  recipientPhoneDetailsSchema,
} from './recipientPhoneDetails';

export interface ReloadlyGiftCardsOrdersRequest {
  productId: number;
  countryCode: string;
  quantity: number;
  unitPrice: number;
  customIdentifier: string;
  senderName: string;
  recipientEmail: string;
  recipientPhoneDetails: RecipientPhoneDetails;
}

export const reloadlyGiftCardsOrdersRequestSchema: Schema<ReloadlyGiftCardsOrdersRequest> = object(
  {
    productId: ['productId', number()],
    countryCode: ['countryCode', string()],
    quantity: ['quantity', number()],
    unitPrice: ['unitPrice', number()],
    customIdentifier: ['customIdentifier', string()],
    senderName: ['senderName', string()],
    recipientEmail: ['recipientEmail', string()],
    recipientPhoneDetails: [
      'recipientPhoneDetails',
      lazy(() => recipientPhoneDetailsSchema),
    ],
  }
);
