/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, Schema, string } from '../schema';
import { RecipientPhone, recipientPhoneSchema } from './recipientPhone';
import { SenderPhone, senderPhoneSchema } from './senderPhone';

export interface ReloadlyAirtimeAsyncTopupRequest {
  operatorId: string;
  amount: string;
  useLocalAmount: boolean;
  customIdentifier: string;
  recipientPhone: RecipientPhone;
  senderPhone: SenderPhone;
}

export const reloadlyAirtimeAsyncTopupRequestSchema: Schema<ReloadlyAirtimeAsyncTopupRequest> = object(
  {
    operatorId: ['operatorId', string()],
    amount: ['amount', string()],
    useLocalAmount: ['useLocalAmount', boolean()],
    customIdentifier: ['customIdentifier', string()],
    recipientPhone: ['recipientPhone', lazy(() => recipientPhoneSchema)],
    senderPhone: ['senderPhone', lazy(() => senderPhoneSchema)],
  }
);
