/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ReloadlyNumberLookupPostRequest {
  number: string;
  countryCode: string;
}

export const reloadlyNumberLookupPostRequestSchema: Schema<ReloadlyNumberLookupPostRequest> = object(
  { number: ['number', string()], countryCode: ['countryCode', string()] }
);
