/**
 * reloadly-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface SenderPhone {
  countryCode: string;
  number: string;
}

export const senderPhoneSchema: Schema<SenderPhone> = object({
  countryCode: ['countryCode', string()],
  number: ['number', string()],
});
